name: Clang-tidy

on:
  push:
      branches:
        -master
  pull_request:
      branches:
      - main
      - master
      - development
      types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request'}}

jobs:
    clang-tidy:
      runs-on: [ubuntu-24.04]

      container:
        image: dealii/dealii:v9.6.0-jammy
        options: --user root

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 30

        - name: Download dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y \
                clang-tidy-18  \
                clang-18

        - name: Run clang-tidy
          run: |
            ./utilities/clang_tidy.sh .

